



<?php
$product=$block->getProductData();
$productStock = $block->getStockItem();
//Zend_Debug::dump($product->getData())
?>



<fieldset form="form1">
    <legend>Add Product:</legend>
    <form action="<?php echo $block->getFormAction () ?>" method="post" enctype="multipart/form-data">

        <label for="product_enable">Product Enable</label>
        <select name="enable">
            <option value="1" selected>Enable</option>
            <option value="0">Disable</option>
        </select>

        <label for="product_name">Product Name</label>
        <input name="product_name" id="product_name" type="text"  required>

        <label for="sku">Sku</label>
        <input name="sku" id="sku" type="text" >

        <label for="short_description">Short Description</label>
        <input name="short_description" id="description" type="text"  required>


        <label for="description">Description</label>
        <textarea name="description" id="description" rows="4" cols="20" maxlength="20" ></textarea>
        <br />
        <br />

        <br/>
        <label for="category">Category</label>
        <br/>



        <br />
        <?php $categories = $block->getStoreCategories (); ?>
        <?php foreach ( $categories as $category ) : ?>
            <label for="category"><?= $category->getName (); ?></label>
            <input type="checkbox" value="<?= $category->getId () ?>" name="category[]">
            <?php
            $subCategories = $block->getChildCategories ( $category->getId () ); ?>
            <br/>
            <?php foreach ( $subCategories as $subCategory ) : ?>

               <label for="category"><?=  $subCategory->getName (); ?></label>
                <input type="checkbox" value="<?= $subCategory->getId () ?>" name="subcategory[]" >
            <br />
            <?php endforeach; ?>
        <?php endforeach; ?>


        <br/>
        <br/>
        <label for="price">Price</label>
        <input name="price" id="price" type="text"  required>
        <br />
        <br />
        <label for="add_image">Add Image</label>
        <input name="test_image" type="file"  required/>
        <br />
        <br />
        <label for="quantity">Quantity</label>
        <input name="quantity" id="quantity" type="text"  required >
        <br />
        <input type="submit" value="ADD">
    </form>
</fieldset>
<?php


?>


<script>
    require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function(jQuery){

        var config = {},
            editor;

        jQuery.extend(config, {
            settings: {
                theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                    'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
                theme_advanced_buttons2: null,
                theme_advanced_buttons3: null,
                theme_advanced_buttons4: null
            }
        });
        editor = new tinyMceWysiwygSetup(
            'description',
            config
        );
        editor.turnOn();
        jQuery('#description')
            .addClass('wysiwyg-editor')
            .data(
                'wysiwygEditor',
                editor
            );
    });
</script>

